# Generated by Django 5.0 on 2024-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_address',
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
